# Generated by Django 6.0.5 on 2026-05-06 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название площадки')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('surface_type', models.CharField(max_length=100, verbose_name='Тип покрытия')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200, verbose_name='Название организации')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('experience_description', models.TextField(verbose_name='Описание опыта')),
                ('document', models.FileField(upload_to='organizer_documents/', verbose_name='Подтверждающий документ')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус заявки')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('player', 'Игрок команды'), ('captain', 'Капитан команды'), ('organizer', 'Организатор турниров'), ('admin', 'Администратор')], default='user', max_length=20, verbose_name='Роль')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Email подтверждён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название команды')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('game_format', models.CharField(choices=[('5x5', '5x5'), ('6x6', '6x6'), ('8x8', '8x8'), ('11x11', '11x11')], max_length=10, verbose_name='Формат игры')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain_teams', to=settings.AUTH_USER_MODEL, verbose_name='Капитан')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Позиция')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('number', models.PositiveIntegerField(verbose_name='Игровой номер')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('left', 'Покинул команду'), ('removed', 'Удалён из команды')], default='active', max_length=20, verbose_name='Статус игрока')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата вступления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.team', verbose_name='Команда')),
            ],
        ),
        migrations.CreateModel(
            name='TeamJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Позиция')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('number', models.PositiveIntegerField(verbose_name='Игровой номер')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team', verbose_name='Команда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название турнира')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('game_format', models.CharField(choices=[('5x5', '5x5'), ('6x6', '6x6'), ('8x8', '8x8'), ('11x11', '11x11')], max_length=10, verbose_name='Формат игры')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('rules', models.TextField(blank=True, verbose_name='Правила участия')),
                ('confirmation_document', models.FileField(upload_to='tournament_documents/', verbose_name='Подтверждающий документ турнира')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Подтверждён'), ('rejected', 'Отклонён'), ('registration', 'Идёт набор команд'), ('active', 'Активен'), ('finished', 'Завершён')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
                ('stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stadium', verbose_name='Площадка')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField(verbose_name='Дата и время матча')),
                ('score_team1', models.PositiveIntegerField(blank=True, null=True, verbose_name='Счёт команды 1')),
                ('score_team2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Счёт команды 2')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('played', 'Сыгран'), ('cancelled', 'Отменён')], default='scheduled', max_length=20, verbose_name='Статус матча')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stadium', verbose_name='Площадка')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='core.team', verbose_name='Команда 1')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='core.team', verbose_name='Команда 2')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament', verbose_name='Турнир')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team', verbose_name='Команда')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament', verbose_name='Турнир')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament', verbose_name='Турнир')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
